version: "3.1"
services:
  receiver:
    build: ./receiver
    restart: always
    ports:
    - "3000:3000"
    environment:
      # Fix SSL shit
      DATABASE_URL: postgres://postgres:S3cret@db:5432/postgres?sslmode=disable
      GITHUB_WEBHOOK_SECRET: MyGitHubSuperSecretSecrect
      WEBHOOK_TABLE: webhooks

  db:
    build: ./postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
  






